import os
import json

repo_dir = r"C:\Users\pokla\STT-fork"
data_dir = os.path.join(repo_dir, "kvizy", "data")
os.makedirs(data_dir, exist_ok=True)

quizzes = {
    "sps": [
        {"q": "Jaký je hlavní účel ložisek v převodovkách?", "options": ["Snižovat hmotnost hřídele", "Zajišťovat přenos tepla", "Zachycovat radiální a axiální síly a snižovat tření", "Zvyšovat kroutící moment"], "correct": 2, "explanation": "Ložiska umožňují uložení rotujících součástí (hřídelů) v rámu, snižují tření a přenášejí síly z hřídele na skříň."},
        {"q": "Co znamená u závitu označení M12?", "options": ["Trubkový závit s průměrem 12 palců", "Metrický závit s velkým průměrem 12 mm", "Jemný metrický závit s průměrem 12 mm", "Lichoběžníkový závit o stoupání 12 mm"], "correct": 1, "explanation": "Písmeno M označuje metrický závit (vrcholový úhel 60°) a číslo 12 jeho velký (vnější) průměr v milimetrech."},
        {"q": "Z čeho se skládá modul ozubeného kola (m)?", "options": ["Je to podíl rozteče (p) a Ludolfova čísla (π)", "Je to průměr roztečné kružnice dělený šířkou zubu", "Je to součin počtu zubů a průměru", "Je to poměr otáček hnacího a hnaného kola"], "correct": 0, "explanation": "Modul ozubení m = p / π. Je to normalizovaná hodnota, dvě do sebe zabírající kola musí mít stejný modul."},
        {"q": "Jakou funkci má 'pero' (např. pero těsné) ve spojení hřídele s nábojem?", "options": ["Přenáší kroutící moment mezi hřídelí a nábojem", "Zajišťuje součástku proti axiálnímu posunutí", "Těsní olej uvnitř převodovky", "Působí jako pružina"], "correct": 0, "explanation": "Pero (pero těsné, Woodruffovo) tvoří tvarový spoj, který zachycuje a přenáší kroutící moment."},
        {"q": "Co je to 'hydrodynamická spojka'?", "options": ["Spojka fungující na principu tření lamel", "Spojka přenášející moment kinetickou energií kapaliny (čerpadlo a turbína)", "Pevná spojka pro spojení dvou souosých hřídelů", "Zubová spojka ovládaná tlakem oleje"], "correct": 1, "explanation": "Hydrodynamická spojka se skládá z čerpadlového a turbínového kola a přenáší výkon plynule pomocí kapaliny."},
        {"q": "Co označuje číslo '8.8' na hlavičce pevnostního šroubu?", "options": ["Délku a průměr šroubu", "Materiál (nerezová ocel)", "Mez pevnosti 800 MPa a mez kluzu 640 MPa (80% z 800)", "Hmotnost šroubu v gramech"], "correct": 2, "explanation": "První číslo (8) x 100 = Mez pevnosti v tahu Rm [MPa]. Druhé číslo (8) znamená, že mez kluzu Re je 80 % z Rm."},
        {"q": "Jaký je princip evolventního ozubení?", "options": ["Zuby mají tvar kružnice", "Zuby jsou tvořeny evolventou křivky (odvalování přímky po základní kružnici)", "Zuby jsou rovné lichoběžníky", "Zuby se nedotýkají vůbec"], "correct": 1, "explanation": "Boky zubů většiny ozubených kol jsou tvořeny evolventou, což zajišťuje konstantní převodový poměr a plynulý záběr."},
        {"q": "K čemu slouží křížový kloub (Kardanův kloub)?", "options": ["Ke spojení dvou různoběžných hřídelů, jejichž úhel se může i měnit", "K utěsnění hřídele proti úniku oleje", "Ke spojení hřídelů pro snížení otáček na polovinu", "Ke kompenzaci teplotní roztažnosti"], "correct": 0, "explanation": "Kardanův kloub umožňuje přenos rotačního pohybu mezi hřídeli, které nejsou v ose a svírají spolu určitý úhel."},
        {"q": "Co je to 'náprava' oproti 'hřídeli'?", "options": ["Náprava je silnější", "Náprava nepřenáší kroutící moment (není namáhána na krut, jen na ohyb), hřídel ano", "Hřídel se na rozdíl od nápravy netočí", "Je to to samé"], "correct": 1, "explanation": "Hřídel přenáší kroutící moment a je namáhána na krut i ohyb. Náprava nese kola (je namáhána na ohyb), ale kroutící moment nepřenáší."},
        {"q": "Jaký typ řemenu se používá v automobilovém průmyslu pro přesné rozvody motoru?", "options": ["Klínový řemen", "Plochý řemen", "Ozubený řemen", "Kruhový řemen"], "correct": 2, "explanation": "Ozubený řemen se nesmeká (tvarový styk) a zajišťuje přesnou synchronizaci klikového a vačkového hřídele."},
        {"q": "K čemu slouží synchronizační spojka v manuální převodovce?", "options": ["K automatickému řazení nahoru", "K vyrovnání obvodových rychlostí ozubených kol před jejich zasunutím do záběru", "K propojení přední a zadní nápravy", "K tlumení rázů motoru"], "correct": 1, "explanation": "Synchronizační spojka využívá třecí kužely k plynulému vyrovnání otáček kol a hřídele, čímž zabraňuje 'škrtání' zubů při řazení."},
        {"q": "Jak funguje hydrostatický převod?", "options": ["Přenáší energii pomocí tlaku kapaliny (hydraulické čerpadlo -> hydromotor)", "Přenáší energii kinetickou silou proudu kapaliny", "Přenáší sílu podtlakem", "Jedná se o klasickou mechanickou převodovku v olejové lázni"], "correct": 0, "explanation": "Hydrostatický převod generuje tlak (hydraulické čerpadlo), který se v hydromotoru opět mění na mechanickou práci."},
        {"q": "Kde se s výhodou používá šnekové soukolí?", "options": ["Při požadavku na velké otáčky bez přenosu síly", "Kde potřebujeme kříživoběžné hřídele a velký převodový poměr (až samosvornost)", "U jízdních kol a motocyklů", "Když potřebujeme soukolí s účinností 99%"], "correct": 1, "explanation": "Šnekové soukolí se používá u hřídelů křížících se v úhlu 90°, poskytuje velký převod do pomala na malém prostoru a může být samosvorné."},
        {"q": "Který mechanismus převede rotační pohyb na přímočarý vratný?", "options": ["Planetová převodovka", "Klikový mechanismus (nebo vačkový)", "Variátor", "Kardanova hřídel"], "correct": 1, "explanation": "Klikový mechanismus (ojnice, klika, píst) konvertuje posuvný pohyb na rotační (spalovací motor) nebo naopak (kompresor, čerpadlo)."},
        {"q": "Co udává zdvihový objem válce (tzv. kubatura)?", "options": ["Celý objem válce včetně kompresního prostoru", "Objem určený průměrem válce a vzdáleností mezi horní a dolní úvratí pístu (Vz = (π*d^2)/4 * z)", "Množství paliva spotřebovaného za minutu", "Objem chladící kapaliny motoru"], "correct": 1, "explanation": "Zdvihový objem je rozdíl objemu válce mezi dolní a horní úvratí pístu. Větší objem obvykle znamená vyšší točivý moment motoru."}
    ],
    "mec": [
        {"q": "Jaký je vzorec pro výpočet normálového napětí (σ) v tahu?", "options": ["σ = F * A", "σ = F / A", "σ = M / W", "σ = E * F"], "correct": 1, "explanation": "Normálové napětí v tahu nebo tlaku se vypočítá jako podíl síly (F) a průřezové plochy (A)."},
        {"q": "Co popisuje Hookeův zákon?", "options": ["Pružnou (elastickou) deformaci materiálu (σ = E * ε)", "Tření dvou ploch proti sobě", "Rovnováhu momentů na páce", "Zpevnění materiálu po překročení meze kluzu"], "correct": 0, "explanation": "Hookeův zákon definuje lineární závislost mezi napětím (σ) a poměrným prodloužením (ε) v oblasti pružné deformace pomocí modulu pružnosti (E)."},
        {"q": "Kde se u ohýbaného nosníku vyskytuje maximální normálové napětí?", "options": ["V neutrální ose (uprostřed průřezu)", "V místě podpor (reakcí)", "V krajních vláknech průřezu (nejdále od neutrální osy)", "V těžišti nosníku"], "correct": 2, "explanation": "Při ohybu je neutrální osa bez napětí, zatímco vlákna na okraji profilu jsou natahována nebo stlačována největší silou (σ_max = M / W)."},
        {"q": "Co vyjadřuje Wöhlerova křivka?", "options": ["Závislost síly na prodloužení u tahové zkoušky", "Závislost rozkmitu napětí na počtu cyklů do únavového lomu", "Rychlost chladnutí kalené oceli", "Grafické znázornění těžiště nepravidelných ploch"], "correct": 1, "explanation": "Wöhlerova křivka znázorňuje únavu materiálu. Ukazuje, po kolika cyklech střídavého namáhání praskne vzorek při daném napětí, a definuje tzv. mez únavy."},
        {"q": "Jaký vliv má vrub (zápich, díra, ostrý přechod) na pevnost součásti?", "options": ["Zvyšuje pevnost materiálu", "Způsobuje koncentraci napětí a výrazně snižuje únavovou pevnost", "Nemá vliv na pevnost, mění jen hmotnost", "Prodlužuje životnost"], "correct": 1, "explanation": "Vrub funguje jako 'koncentrátor napětí', kde se napětí lokálně extrémně zvýší. U střídavého namáhání je to nejčastější iniciátor únavových trhlin."},
        {"q": "Co znamená vzpěrná pevnost (vzpěr)?", "options": ["Namáhání dlouhého a štíhlého prutu tlakem, při kterém hrozí jeho vybočení (zhroucení)", "Namáhání hřídele kroutícím momentem", "Pružné protažení šroubu", "Zkouška tvrdosti"], "correct": 0, "explanation": "Vzpěr je stav ztráty stability u dlouhých štíhlých prutů (např. sloup, pístnice), kdy se prut při tlakovém zatížení ohne do strany ještě dříve, než se materiál rozdrtí."},
        {"q": "Jaký vztah platí pro výpočet momentu síly (M)?", "options": ["M = m * a", "M = F * r (síla krát rameno)", "M = F / S", "M = v * t"], "correct": 1, "explanation": "Moment síly je dán velikostí působící síly a délkou ramene, na kterém síla působí kolmo k ose otáčení."},
        {"q": "Co znamená třetí Newtonův zákon (Zákon akce a reakce)?", "options": ["Těleso setrvává v klidu nebo rovnoměrném pohybu, dokud není donuceno stav změnit", "Zrychlení tělesa je úměrné síle", "Každá síla (akce) vyvolává stejně velkou sílu opačného směru (reakci)", "Třecí síla závisí na normálové síle"], "correct": 2, "explanation": "Když působí těleso 1 na těleso 2 silou (akcí), působí současně těleso 2 na těleso 1 stejně velkou silou (reakcí) opačného směru."},
        {"q": "Kdy nastává smykové namáhání?", "options": ["Když na těleso působí dvojice sil stejného směru mimo osu", "Když dvě rovnoběžné, těsně u sebe ležící síly působí proti sobě a mají snahu materiál přestřihnout", "Při kroucení hřídele", "Když tahová síla protáhne prut o 10%"], "correct": 1, "explanation": "Smyk (střih) vzniká působením posouvajících sil v rovině průřezu. Typickým případem jsou čepy, nýty nebo stříhání plechu."},
        {"q": "Co je to Modul pružnosti v tahu (E, tzv. Youngův modul)?", "options": ["Je to konstanta materiálu vyjadřující jeho tuhost (odpor proti pružné deformaci)", "Je to maximální pevnost v tahu (Rm)", "Je to tloušťka materiálu po ohybu", "Udává, o kolik procent se materiál prodlouží do přetržení"], "correct": 0, "explanation": "Youngův modul (E) je mírou tuhosti materiálu. Ocel má E cca 210 000 MPa, hliník jen cca 70 000 MPa (je poddajnější)."},
        {"q": "Co udává Poissonovo číslo (μ nebo ν)?", "options": ["Závislost pevnosti a teploty", "Poměr příčného zúžení k podélnému prodloužení při tahovém namáhání", "Koeficient statického tření mezi ocelí a litinou", "Počet zkoušek potřebných pro Wöhlerovu křivku"], "correct": 1, "explanation": "Když prut natáhnete, nejen že se prodlouží, ale také zúží v průměru. Tento poměr popisuje Poissonovo číslo (u oceli obvykle 0.3)."},
        {"q": "Soustava sil působících v rovině do jednoho bodu je v rovnováze, když...", "options": ["Jsou všechny síly rovnoběžné", "Součet velikostí všech sil se rovná hmotnosti tělesa", "Vektorový součet všech sil je roven nule (součet x-ových i y-ových složek = 0)", "Žádná síla na těleso nepůsobí"], "correct": 2, "explanation": "Pro rovnováhu bodu musí platit suma Fx = 0 a suma Fy = 0."},
        {"q": "Který parametr průřezu určuje jeho tuhost proti ohybu?", "options": ["Plocha průřezu (A)", "Kvadratický moment průřezu (Ix, Iy)", "Průřezový modul v ohybu (W)", "Hustota materiálu (ρ)"], "correct": 1, "explanation": "Kvadratický moment průřezu (I) závisí na tvaru profilu a rozložení hmoty od neutrální osy. Čím více hmoty je dál od osy (I-profil), tím lépe odolává ohybu."},
        {"q": "Na co se používá Steinerova věta?", "options": ["K výpočtu otáček na CNC stroji", "K výpočtu modulu pružnosti E", "K výpočtu kvadratického momentu průřezu k ose, která neprochází jeho těžištěm", "K určení tažnosti materiálu"], "correct": 2, "explanation": "Steinerova věta umožňuje vypočítat kvadratický moment plochy ke zvolené ose tím, že k momentu k těžišťové ose přičteme součin plochy a čtverce vzdálenosti obou os."},
        {"q": "Jaký průřez hřídele nejlépe přenáší namáhání krutem vzhledem ke své hmotnosti?", "options": ["Plný kruh", "Dutý kruh (trubka)", "Čtverec", "Obdélník"], "correct": 1, "explanation": "Při krutu je napětí největší na vnějším okraji a směrem ke středu klesá k nule. Materiál uprostřed nepracuje, proto je trubka mnohem efektivnější z hlediska úspory hmotnosti."}
    ],
    "cnc": [
        {"q": "K čemu slouží kód G00?", "options": ["Příkaz pro spuštění chlazení", "Rychloposuv nástroje na požadované souřadnice bez obrábění materiálu", "Lineární pracovní posuv, kdy nástroj řeže do kovu", "Kruhová interpolace"], "correct": 1, "explanation": "G00 přesune nástroj maximální konstrukční rychlostí stroje na zadanou pozici. Nesmí se používat, pokud je nástroj v kontaktu s polotovarem."},
        {"q": "Jak se programuje pracovní posuv po přímce (soustružení válce nebo kužele)?", "options": ["G00 X.. Z..", "G01 X.. Z.. F..", "G02 X.. Z..", "G04 X.."], "correct": 1, "explanation": "G01 (Lineární interpolace) posouvá nástroj po přímce zadanou rychlostí posuvu (F)."},
        {"q": "Při kruhové interpolaci G02 se nástroj pohybuje...", "options": ["Proti směru hodinových ručiček", "Rychloposuvem mimo materiál", "Po směru hodinových ručiček", "Cik-cak pohybem nahoru a dolů"], "correct": 2, "explanation": "G02 generuje pohyb po kruhovém oblouku po směru chodu hodinových ručiček (CW). Písmeno G03 se používá pro směr opačný (CCW)."},
        {"q": "Co znamená adresa 'F' v NC programu?", "options": ["Force - Síla upnutí sklíčidla", "Feed - Rychlost posuvu (např. mm/ot nebo mm/min)", "Function - Pomocná funkce stroje", "File - Jméno uloženého programu"], "correct": 1, "explanation": "Adresa F (Feed) určuje rychlost, jakou se posouvá nástroj do řezu (posuv)."},
        {"q": "Co způsobí kód M03 na soustruhu?", "options": ["Konec programu", "Otevření dveří krytu", "Zastavení vřetene", "Roztočení vřetene po směru hodinových ručiček (CW)"], "correct": 3, "explanation": "M03 roztočí vřeteno (univerzálu s obrobkem) ve směru hodinových ručiček. M04 ho točí opačně a M05 ho zastaví."},
        {"q": "Pro jaký úkon slouží kód M08?", "options": ["Zastavení vřetene", "Spuštění přívodu chladící kapaliny", "Volba nástroje z výměníku", "Konec programu (M30)"], "correct": 1, "explanation": "M08 se používá pro zapnutí chlazení (čerpadla). Chlazení se vypíná kódem M09."},
        {"q": "Kde se u soustruhu obvykle nachází 'Nulový bod obrobku' (W)?", "options": ["Přesně v geometrickém středu vřetene", "Na levé ploše univerzálky (sklíčidla)", "Volí ho programátor, obvykle na pravém čele a v ose symetrie obrobku (Z=0, X=0)", "Kdekoliv v hale"], "correct": 2, "explanation": "Nulový bod obrobku (W) se definuje tak, aby se od něj snadno počítaly kóty. U soustruženého rotačního dílce je to typicky průsečík osy rotace a pravé čelní plochy."},
        {"q": "Co je to korekce poloměru špičky nástroje (G41 / G42)?", "options": ["Program ignoruje souřadnice Z", "Systém automaticky přepočítává dráhu tak, aby se kompenzovalo zakulacení břitu (R) a nevznikaly chyby při soustružení kuželů či oblouků", "Stroj sám opraví rozbitý nůž", "Zastaví stroj, pokud se nůž zlomí"], "correct": 1, "explanation": "Špička nože není absolutně ostrá (má rádius např. 0.4mm). Pokud bychom jeli kónusy nebo oblouky bez kompenzace G41/G42, vznikaly by rozměrové odchylky."},
        {"q": "Který parametr zadává u soustruhu příkaz G96 S200?", "options": ["Konstantní otáčky 200 ot/min", "Konstantní řeznou rychlost 200 m/min", "Zastavení programu na 200 sekund", "Hloubku řezu 200 mikronů"], "correct": 1, "explanation": "G96 zapíná konstantní řeznou rychlost (v_c). Stroj bude sám zrychlovat otáčky vřetene tím víc, čím blíž k ose rotace (X=0) bude nůž zajíždět."},
        {"q": "Jaký je rozdíl mezi absolutním (G90) a inkrementálním (G91) programováním u frézky?", "options": ["Absolutní bere počátek stále v nulovém bodě, inkrementální počítá každý krok od poslední pozice nástroje", "Absolutní programují stroje samy, inkrementální člověk", "Neexistuje rozdíl", "Inkrementální používá palce místo milimetrů"], "correct": 0, "explanation": "Při G90 znamenají souřadnice polohu vůči nulovému bodu (obrobku). Při G91 udávají přírůstek (o kolik mm se má pohnout z nynějšího místa)."],
        {"q": "K čemu se využívají přednastavené pevné cykly (např. G81, G83)?", "options": ["Zajišťují úklid stroje", "Pro zjednodušení programování opakujících se složitějších operací (např. vrtání děr s výplachem, hluboké vrtání)", "Zastavují cyklus obrábění", "Odesílají data na server"], "correct": 1, "explanation": "Cyklus je zabalená sada příkazů. Místo programování mnoha řádků sjíždění a vyjíždění pro vrtání děr napíšeme jeden řádek cyklu (např. G83 pro vrtání s lámačem třísky)."},
        {"q": "Kód G04 s parametrem X (nebo P) se používá k:", "options": ["Roztočení vřetene na max", "Časové prodlevě (zastavení posuvu na zadanou dobu, nástroj se ale točí dál)", "Výměně chladící kapaliny", "Volbě polotovaru z knihovny"], "correct": 1, "explanation": "Časová prodleva (prodleva dlení) G04 (např. G04 X2 = pauza 2 sekundy). Používá se např. na dně slepé díry k 'vyhlazení' obrobeného povrchu."},
        {"q": "Jak se v programu označují čísla řádků (bloků)?", "options": ["Písmenem O", "Písmenem G", "Písmenem N (např. N10, N20)", "Písmenem S"], "correct": 2, "explanation": "Bloky programu se číslují adresou N. Často se skáče po deseti (N10, N20, N30) proto, aby se daly případně dopisovat zapomenuté řádky (N15)."},
        {"q": "Co znamená 'Postprocesor' v prostředí CAD/CAM (např. EdgeCAM, AlphaCAM)?", "options": ["Chladící zařízení stroje", "Softwarový převodník, který přeloží vygenerované dráhy nástroje do G-kódu přesně pro konkrétní CNC řídící systém (Sinumerik, Heidenhain, Fanuc...)", "Poslední operace na obrobku (leštění)", "Editor PDF výkresů"], "correct": 1, "explanation": "Každý řídící systém u CNC stroje (Sinumerik, Heidenhain...) mluví nepatrně jiným 'dialektem' G-kódu. Postprocesor zajistí překlad do toho správného jazyka."},
        {"q": "Co udělá kód M06?", "options": ["Konec programu s přetočením na začátek", "Zapnutí čtvrté osy C", "Výměna nástroje", "Konec hrubování"], "correct": 2, "explanation": "M06 je příkaz pro výměnu nástroje. Obvykle mu předchází odjetí do bezpečné vzdálenosti a předvolba nástroje (např. T02 M06 - vlož nástroj číslo 2)."}
    ],
    "mte": [
        {"q": "Jaký je základní princip pneumatiky?", "options": ["Využití tekutého kovu pro přenos výkonu", "Přeměna energie stlačeného vzduchu na mechanickou práci", "Využití gravitace k pohybu ventilů", "Elektrické lineární motory s baterií"], "correct": 1, "explanation": "Pneumatické systémy využívají tlakovou energii stlačeného vzduchu, která je v pneumotoru (válci) přeměněna na mechanickou práci."},
        {"q": "Jaký je hlavní rozdíl mezi pneumatikou a hydraulikou z fyzikálního hlediska?", "options": ["Pneumatika je mnohem dražší než hydraulika", "Kapaliny v hydraulice jsou prakticky nestlačitelné, vzduch v pneumatice stlačitelný je", "Hydraulika nepřenáší velké síly", "Pneumatika neumožňuje lineární pohyb"], "correct": 1, "explanation": "Vzduch (plyn) lze snadno stlačit (mění objem), olej (kapalina) nikoliv. Proto se v hydraulice dosahuje vysokých a tuhých tlakových sil, zatímco pneumatika je 'odpružená'."},
        {"q": "Jednočinný pneumatický válec se vyznačuje tím, že:", "options": ["Může pracovat tlakem v obou směrech (vysouvat i zasouvat)", "Práci koná stlačeným vzduchem jen v jednom směru, vrací se obvykle vestavěnou pružinou", "Nemá pístní tyč", "Funguje i bez kompresoru"], "correct": 1, "explanation": "Jednočinný válec má jen jeden přívod vzduchu. Pohyb jedním směrem dělá tlak vzduchu, návrat zpět obstará vnitřní vratná pružina nebo vnější zátěž."},
        {"q": "K čemu slouží rozváděč označený 5/2?", "options": ["Má 5 ventilů a 2 písty", "Přenese tlak 5 bar za 2 sekundy", "Má 5 cest (připojení) a 2 pracovní polohy (stavy)", "Dělí výkon kompresoru 5/2"], "correct": 2, "explanation": "V pneumatických schématech určuje první číslo počet připojovacích otvorů (portů) a druhé číslo počet přepínatelných pozic šoupátka."},
        {"q": "Jaký je vztah mezi tlakem (p), silou (F) a plochou (S)?", "options": ["F = p / S", "p = F * S", "p = F / S", "S = p * F"], "correct": 2, "explanation": "Tlak vzniká působením síly na určitou plochu (p = F/S). Vzorec pro výpočet síly pístu pak je F = p * S."},
        {"q": "Co znamená škrtící ventil s jednosměrným zpětným ventilem?", "options": ["Filtruje vzduch od prachu", "V jednom směru průtok stlačeného vzduchu brzdí (škrtí) a v opačném směru ho pouští bez omezení volně", "Nepouští vzduch nikam, tvoří tlakovou zátku", "Slouží k mazání válce"], "correct": 1, "explanation": "Používá se zejména k regulaci rychlosti vysouvání/zasouvání pístu - reguluje odvětrávání vzduchu z válce pryč."},
        {"q": "Kde se nejlépe uplatní hydraulické systémy (oproti pneumatickým)?", "options": ["Tam, kde potřebujeme ohromné síly, přesné polohování a tuhost (lisy, bagry)", "V rychlých třídících linkách a manipulátorech do 1 kg", "V čistých provozech v potravinářství, kde hrozí únik oleje", "Při foukání trubek"], "correct": 0, "explanation": "Olej je nestlačitelný, hydraulika umožňuje extrémní pracovní tlaky (až 300+ barů) a generuje obrovské zdvihové síly bez 'pružení'."},
        {"q": "K čemu slouží v pneumatické přípravné jednotce redukční ventil (regulátor tlaku)?", "options": ["Vyrábí stlačený vzduch", "Zachytává kondenzát (vodu)", "Sníží a udržuje stálý pracovní tlak pro daný stroj, i když kolísá tlak v centrálním rozvodu", "Přimíchává do vzduchu olejový mlženec"], "correct": 2, "explanation": "Z rozvodu jde např. 8 bar, redukční ventil zaručí, že stroj dostane stabilních 6 bar, aby nástroje fungovaly spolehlivě a neskákaly."},
        {"q": "Dvojčinný válec o průměru 50mm (plocha S1) a s pístnicí o průměru 20mm (plocha pístnice s2) bude mít:", "options": ["Výsuvnou a zásuvnou sílu úplně stejnou", "Větší sílu při zasouvání než při vysouvání", "Větší sílu při vysouvání (tlak působí na celou plochu S1), než při zasouvání (plocha je omezena o pístnici: S1 - s2)", "Nulovou sílu, protože se tlaky vyruší"], "correct": 2, "explanation": "Tlak se opírá o plochu. Při zasouvání překáží průřez pístní tyče, takže plocha (a tím pádem i síla a spotřeba vzduchu) je menší."},
        {"q": "Co to je 'logický člen AND' (Dvoutlakový ventil) v pneumatice?", "options": ["Generátor náhodných signálů", "Součástka, která propustí vzduch k válci POUZE tehdy, jsou-li stisknuta obě dvě tlačítka (např. dvouruční bezpečností spouštění lisu)", "Ventil pro snížení hluku odfuku", "Zvýší tlak z kompresoru"], "correct": 1, "explanation": "Funkce logického součinu (AND). Výstup (Y) je aktivní pouze při signálu A i B současně."},
        {"q": "Co znamená zkratka FRL v pneumatické přípravné jednotce?", "options": ["Fast, Reliable, Low-cost", "Friction, Rotation, Linear", "Filter, Regulator, Lubricator (Filtr, Redukční ventil, Maznice)", "Force Response Logic"], "correct": 2, "explanation": "Každý vzduch přicházející do stroje musí projít úpravnou jednotkou: vyfiltrovat vlhkost a prach, nastavit správný tlak, a u starších systémů s gumovým těsněním přimazat."},
        {"q": "Jaká vlastnost oleje je u hydrauliky klíčová pro výpočty ztát v hadicích?", "options": ["Jiskřivost", "Viskozita (vnitřní tření a odpor kapaliny proti tečení)", "Tvrdost", "Hořlavost"], "correct": 1, "explanation": "Příliš hustý olej (vysoká viskozita) v mrazu teče pomalu a čerpadlo ho neutáhne, příliš řídký (horký) nepromazává a utíká z těsnění."},
        {"q": "Z čeho se skládá klasický zubové hydrogenerátor (čerpadlo)?", "options": ["Ze dvou ozubených kol v těsné skříni, která přenáší olej ve volném prostoru mezi zuby po obvodu", "Z jednoho velkého pístu a hřídele s vačkou", "Z klikové hřídele a turbíny", "Z větráku a sacího koše"], "correct": 0, "explanation": "Zubová čerpadla sají olej do mezer mezi zuby a tělesem čerpadla a přemisťují ho po obvodu (ne středem!) z prostoru sání na výtlak."},
        {"q": "Proč je stlačený vzduch z hlediska ekonomiky považován za velmi drahé médium?", "options": ["Protože je do něj nutné přimíchávat zlato", "Účinnost přeměny elektřiny kompresorem na tlakový vzduch je velmi nízká (velká část jde do ztrátového tepla) a úniky jsou drahé", "Protože jsou trubky velmi drahé na instalaci", "Protože kompresory spotřebují spoustu drahé vody"], "correct": 1, "explanation": "Až 90% elektrické energie při kompresi vzduchu se přemění na teplo. Každá syčící netěsnost stojí obrovské peníze."},
        {"q": "Co má za úkol zpětný ventil s pružinou v hydraulickém obvodu?", "options": ["Otáčet tokem oleje doprava nebo doleva", "Zabránit přetížení obvodu a propustit olej do nádrže při přetlaku (to dělá pojistný ventil!)", "Umožnit průtok oleje pouze jedním směrem a ve druhém směru jej spolehlivě uzavřít", "Zahřívat olej při zimních startech"], "correct": 2, "explanation": "Zpětný ventil se otevírá silou kapaliny proti slabé pružince. Jakmile kapalina zatlačí opačně, ventil zapadne do sedla a průtok utěsní."}
    ]
}

for subj, q_list in quizzes.items():
    filepath = os.path.join(data_dir, f"{subj}.json")
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(q_list, f, ensure_ascii=False, indent=2)

print("Kvizy data created.")
